easy_admin:
    site_name: '<em style="font-size: 80%">ParamÃ©trage</em> <span style="font-size: 20%"><a href="http://localhost:8000" style="font-size: 50%" class="text-primary">Quitter</a></span>'
    design:
      assets:
        css: ['css/custom_backend.css']
    user:
        display_name: true
        display_avatar: false
        name_property_path: 'username'


